### ISSUE TITLE
standard_init_linux.go:219: exec user process caused: exec format error

### ISSUE THREAD

**Issue by Nicolaas0411** [BruceLeeu/rpc-assignment#1]
Hi,

Code looks good. Thanks for putting in so much effort. Please see the below log statement when I try to run the docker file. Let me know if you need any assistance. Please let me know when it is fix so that I can review it.

`➜  rpc-assignment git:(master) docker build -t rpc-assignment .
[+] Building 132.1s (15/15) FINISHED                                                                                                                                              
 => [internal] load build definition from Dockerfile                                                                                                                         0.5s
 => => transferring dockerfile: 719B                                                                                                                                         0.0s
 => [internal] load .dockerignore                                                                                                                                            0.7s
 => => transferring context: 2B                                                                                                                                              0.0s
 => [internal] load metadata for docker.io/library/python:3.9                                                                                                                4.5s
 => [auth] library/python:pull token for registry-1.docker.io                                                                                                                0.0s
 => [internal] load build context                                                                                                                                            0.6s
 => => transferring context: 2.08kB                                                                                                                                          0.0s
 => [1/9] FROM docker.io/library/python:3.9@sha256:168fd55b03929f88cd3e1e05b9ebe8f9cc1c095af8b53a8c0cd50da04a8c3a40                                                         41.6s
 => => resolve docker.io/library/python:3.9@sha256:168fd55b03929f88cd3e1e05b9ebe8f9cc1c095af8b53a8c0cd50da04a8c3a40                                                          0.0s
 => => sha256:168fd55b03929f88cd3e1e05b9ebe8f9cc1c095af8b53a8c0cd50da04a8c3a40 2.36kB / 2.36kB                                                                               0.0s
 => => sha256:bd2d782a1d06f3a5d94f9a37bbf9ffe8a78b56bf61f0d9a370e4c2752ecf1dd0 2.22kB / 2.22kB                                                                               0.0s
 => => sha256:399d79b9981c054aaeb961bf0662bc5157040ef71cdd6be4159938cfa9df0753 8.33kB / 8.33kB                                                                               0.0s
 => => sha256:90273c85fdda8648cee9282aa7b01faf0ec1f45451931985b3504c37cf1ac3e6 7.69MB / 7.69MB                                                                               1.2s
 => => sha256:e9742a63e95a88f8685c4f23a73f7dd15e4039ac1862ce5753c53406a5f7c04a 49.20MB / 49.20MB                                                                             8.9s
 => => sha256:685f873e984153af9a44cf556c7679b430b9c557d901c7d476725134f28754e7 9.98MB / 9.98MB                                                                               3.6s
 => => sha256:a34041dfaf60ca49c213d83e89205fc2b7e222817c9728a4aa4f7d3f09d579c9 52.17MB / 52.17MB                                                                            16.2s
 => => sha256:c9688107c15585cc88b559730b6668481b4b5d142a662c94868eb4d7fa262a80 183.89MB / 183.89MB                                                                          30.7s
 => => extracting sha256:e9742a63e95a88f8685c4f23a73f7dd15e4039ac1862ce5753c53406a5f7c04a                                                                                    0.7s
 => => sha256:19cd4c327b589f376b28764ad1d8023d14afc52acf212f6874b127a665462e74 6.26MB / 6.26MB                                                                              11.9s
 => => extracting sha256:90273c85fdda8648cee9282aa7b01faf0ec1f45451931985b3504c37cf1ac3e6                                                                                    0.1s
 => => extracting sha256:685f873e984153af9a44cf556c7679b430b9c557d901c7d476725134f28754e7                                                                                    0.1s
 => => sha256:f9caa62d74aa4e15eb5243eb9fa72c92951377e7de3b6d73920a0c4ed601bf97 18.63MB / 18.63MB                                                                            16.7s
 => => extracting sha256:a34041dfaf60ca49c213d83e89205fc2b7e222817c9728a4aa4f7d3f09d579c9                                                                                    1.0s
 => => sha256:001bc94027a277f1d2c7356dff6664e27c136f0155b3740bef87796a0d693c9d 232B / 232B                                                                                  17.2s
 => => sha256:f11dc50aaa23c1729e7cfad53df677c2363e1becd95347fea821083462fcad40 2.16MB / 2.16MB                                                                              18.1s
 => => extracting sha256:c9688107c15585cc88b559730b6668481b4b5d142a662c94868eb4d7fa262a80                                                                                    3.5s
 => => extracting sha256:19cd4c327b589f376b28764ad1d8023d14afc52acf212f6874b127a665462e74                                                                                    0.3s
 => => extracting sha256:f9caa62d74aa4e15eb5243eb9fa72c92951377e7de3b6d73920a0c4ed601bf97                                                                                    0.5s
 => => extracting sha256:001bc94027a277f1d2c7356dff6664e27c136f0155b3740bef87796a0d693c9d                                                                                    0.0s
 => => extracting sha256:f11dc50aaa23c1729e7cfad53df677c2363e1becd95347fea821083462fcad40                                                                                    0.1s
 => [2/9] RUN apt-get update && apt-get install -y --no-install-recommends                                                                                                   4.3s
 => [3/9] RUN apt-get install rabbitmq-server -y                                                                                                                            64.0s
 => [4/9] WORKDIR /usr/src/app                                                                                                                                               0.7s 
 => [5/9] COPY requirements.txt .                                                                                                                                            0.6s 
 => [6/9] RUN pip install --upgrade pip && pip install -r requirements.txt                                                                                                   8.6s 
 => [7/9] COPY service.py .                                                                                                                                                  0.7s 
 => [8/9] COPY dockerrun.sh /usr/local/bin/dockerrun.sh                                                                                                                      0.6s 
 => [9/9] RUN chmod +x /usr/local/bin/dockerrun.sh                                                                                                                           1.2s 
 => exporting to image                                                                                                                                                       3.9s 
 => => exporting layers                                                                                                                                                      3.4s 
 => => writing image sha256:e5db0af25370269b9d54c5f364d16ceed7164964ba7299ee0ab25d7a52076504                                                                                 0.0s 
 => => naming to docker.io/library/rpc-assignment                                                                                                                            0.0s
➜  rpc-assignment git:(master) docker run -d -it --name rpc-assignment rpc-assignment
70c557007eaa5ce28e8d453de9a6057f5f89347ba99293157dba063d0f07f39e
➜  rpc-assignment git:(master) docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
➜  rpc-assignment git:(master) docker rm 70c557007eaa5ce28e8d453de9a6057f5f89347ba99293157dba063d0f07f39e
70c557007eaa5ce28e8d453de9a6057f5f89347ba99293157dba063d0f07f39e
➜  rpc-assignment git:(master) docker run -it --name rpc-assignment rpc-assignment                    
standard_init_linux.go:219: exec user process caused: exec format error`

**Comment by Nicolaas0411** [comment]
To put you on the right path I think there is something wrong with the dockerrun.sh file.

**Comment by BruceLeeu** [comment]
Thanks for letting me know. I'm on it. I'll let you know when it's done.

> 
> 
> To put you on the right path I think there is something wrong with the dockerrun.sh file.

**Comment by BruceLeeu** [comment]
It seems I accidentally removed the Shebang required at top of the .sh file
I have pushed the fix. Please advise if any other problems occur.

**Comment by Nicolaas0411** [comment]
Nice! Well done. I am happy with the assignment. I will get Kayla to schedule an interview.
